version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: golang:1.23 
    working_dir: /app
    volumes:
      - ./uploads:/app/uploads
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app_db
    command: >
      sh -c "
      go install github.com/cespare/reflex@latest &&
      reflex -r '\.go$' -s go run ./cmd/main.go
      "
volumes:
  db_data:
